package config

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

const starterConfig = `# Generated by Aiharn. Edit this file before starting Aiharn again.
# Local paths resolve relative to this file.

aiharn_home = "~/.aiharn"

[models.default]
provider = "openai_responses"
base_url = "https://api.openai.com/v1"
api_key = "" # required
model = "gpt-5"

[[channels]]
name = "local"
type = "local"

[agents.main]
model = "default"
system_prompt = "prompts/main.md"
channel = "local"
tools = "all"
allow_subagents = true

[approval]
mode = "ask"
`

const starterPrompt = `You are an AI assistant operating through Aiharn.
Help the user complete their task accurately, safely, and efficiently.
`

// EnsureDefaultConfig creates a private starter configuration and its default
// system prompt when path does not exist. Existing files are never overwritten.
// The returned boolean reports whether the configuration was created.
func EnsureDefaultConfig(path string) (bool, error) {
	if _, err := os.Lstat(path); err == nil {
		return false, nil
	} else if !errors.Is(err, fs.ErrNotExist) {
		return false, fmt.Errorf("inspect %s: %w", path, err)
	}

	home := filepath.Dir(path)
	promptsDir := filepath.Join(home, "prompts")
	if err := os.MkdirAll(promptsDir, 0o700); err != nil {
		return false, fmt.Errorf("create %s: %w", promptsDir, err)
	}

	promptPath := filepath.Join(promptsDir, "main.md")
	promptCreated, err := writeExclusive(promptPath, []byte(starterPrompt), 0o600)
	if err != nil {
		return false, fmt.Errorf("create starter prompt: %w", err)
	}

	created, err := writeExclusive(path, []byte(starterConfig), 0o600)
	if err != nil {
		if promptCreated {
			_ = os.Remove(promptPath)
		}
		return false, fmt.Errorf("create starter config: %w", err)
	}
	return created, nil
}

func writeExclusive(path string, data []byte, perm fs.FileMode) (created bool, err error) {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, perm)
	if errors.Is(err, fs.ErrExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	created = true
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = closeErr
		}
		if err != nil {
			_ = os.Remove(path)
		}
	}()
	if _, err = f.Write(data); err != nil {
		return created, err
	}
	return created, nil
}
